@startuml
left to right direction
actor "Monitor" as m
actor "Administrator" as a
actor "System Handler" as s

rectangle RMS {
 (View alarm history) as vh
 (Create new alarm condition) as cna
 (Manage alarms) as ma
 (Modify alarm condition) as mac
 (Delete alarm condition) as dac
 (Create alarm actions) as cac
 (Modify alarm actions) as maca
 (Delete alarm actions) as daca
 (Receive alarm notification on UI) as ra
 (Receive alarm notification on email) as re
 (Continuously check for alarm conditions) as ccac
 (Distributing alarm notifications) as dan
}

m --> vh
m --> ra
m --> re

a --|> m
a --> ma
ma <|-- cna
ma <|-- mac
ma <|-- dac
ma <|-- cac
ma <|-- maca
ma <|-- daca


s --> ccac
s --> dan

@enduml