@startuml
left to right direction
actor "Supervisor" as m
actor "Administrator" as a

rectangle RMS {
 (Monitor production parameter) as mp
 (Modify monitoring PLC Tag) as mm
}

m -- mp
a --|> m
a -- mm

@enduml