@startuml
partition "**usecase** Triggering alarm" {
  start
  note: 1 second FixedDelay trigger
  :Get all existing\nalarm conditions\nin the app;

  repeat
    if (Condition is met?) then (no)
    elseif (Was met for {timeInterval}\nseconds continously?) then (no)
    elseif (No alarm of this alarm\ncondtion yet?) then (no)
    else ()
      :Trigger an alarm of\nthis alarm condition;
    endif
  repeat while (Still alarm condtions?) is (yes)
  -> no;
  :Get all triggered\nalarm;
  repeat
    :Create new Alarm History\nwith status = Triggered;
  repeat while (Still triggered alarm?) is (yes)
  -> no;
  :Get all alarm histories;
  repeat
    if (Alarm history status\n = Triggered) then (yes)
      repeat
        if (action?) then (ui popup)
          :Send UI noti;
        else (email)
          :Send Email;
        endif
      repeat while (Still action?) is (yes)
      -> no;
    else (no)
    endif
    :Set alarm history status = Sent;
    if (Attached condition is not met anymore?) then (yes)
      :Set alarm history status = Solved;
    else (no)
    endif
  repeat while (Still alarm histories?) is (yes)
  -> no;

  stop
}
@enduml
